<a href="https://colab.research.google.com/github/NatGN/Introducci-n-a-Python-Estructuras-condicionales-/blob/main/Practica_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRACTICA PANDAS

Parte 1: Carga y Exploración de Datos
1. Carga de datos: Carga un archivo CSV (por ejemplo, `datos.csv`) utilizando `pandas`.
2. Exploración básica: Muestra las primeras 5 filas, las últimas 5 filas, y un resumen estadístico de los datos.

In [18]:
import pandas as pd
df = pd.read_csv("ModalidadVirtual.csv")
df.head()

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Hombre,Eventual
1,1,2020-11-08,Psicología,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Hombre,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Mujer,Sí
3,3,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,18,Mujer,No
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Hombre,Sí

In [19]:
df.tail()

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,sexo,trabajo
217,230,2020-12-10,Gestión Turística y Hotelera,Si,Horario flexible.,Conexión a internet.,19,Mujer,Sí
218,231,2020-12-11,Ingeniería de Sistemas,No,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",23,Mujer,No
219,232,2020-12-11,Gestión Turística y Hotelera,No,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",25,Hombre,Sí
220,233,2020-12-11,Ingeniería Agronómica,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,20,Mujer,Sí
221,234,2020-12-12,Comercio Internacional,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",23,Hombre,Sí

In [20]:
df.describe()

       Unnamed: 0        edad
count  222.000000  222.000000
mean   119.896396   28.166667
std     67.424522    7.556374
min      0.000000   17.000000
25%     63.250000   22.000000
50%    121.500000   27.000000
75%    177.750000   33.000000
max    234.000000   54.000000

3. Información del DataFrame: Muestra la información del DataFrame (tipos de datos, columnas, etc.).

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  222 non-null    int64
 1   time        222 non-null    object
 2   carrera     222 non-null    object
 3   acepta      222 non-null    object
 4   positivo    222 non-null    object
 5   negativo    222 non-null    object
 6   edad        222 non-null    int64
 7   sexo        222 non-null    object
 8   trabajo     222 non-null    object
dtypes: int64(2), object(7)
memory usage: 15.7+ KB

Parte 2: Limpieza de Datos
1. Muestra la cantidad de valores nulos y eliminar valores faltantes

In [22]:
df.isnull().sum()

Unnamed: 0    0
time          0
carrera       0
acepta        0
positivo      0
negativo      0
edad          0
sexo          0
trabajo       0
dtype: int64

In [23]:
df_sin_nulos = df.dropna()

2. Rellenar valores faltantes: Rellena los valores faltantes con 0.

In [24]:
df_relleno = df.fillna(0)

3. Eliminar columnas innecesarias: Elimina una columna que no sea relevante para el análisis.

In [25]:
df = df.drop(columns=["sexo"])

Parte 3: Filtrado y Selección de Datos
1. Filtrar con múltiples condiciones: Filtra las filas que cumplan con múltiples condiciones.

In [26]:
df_filtrado = df[
    (df["edad"] >= 20) &
    (df["carrera"] == "Ingeniería de Sistemas") &
    (df["acepta"] == "Si")
]

df_filtrado

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,trabajo
0,0,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Eventual
2,2,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Sí
4,4,2020-11-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,39,Sí
7,7,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Sí
8,8,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,20,Sí
9,9,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,25,Sí
11,11,2020-11-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,21,Eventual
33,38,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,45,Sí
37,43,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,39,Sí
38,44,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,22,Eventual
41,48,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,33,Eventual
42,49,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,21,Sí
44,51,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,20,No
46,54,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,26,Sí
47,55,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,21,Eventual
48,56,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,33,Sí
49,57,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",35,Sí
50,58,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,22,Sí
51,59,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,27,Sí
52,60,2020-11-09,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,20,No
53,61,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,33,Sí
55,63,2020-11-09,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,45,Sí
56,64,2020-11-09,Ingeniería de Sistemas,Si,Autonomía.,Conexión a internet.,26,Eventual
60,69,2020-11-10,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,32,Sí
71,81,2020-11-10,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",21,No
80,90,2020-11-10,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,38,Sí
81,91,2020-11-10,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,33,Sí
82,92,2020-11-10,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,33,Sí
83,93,2020-11-11,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,30,Sí
89,100,2020-11-13,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,"Falta de recursos de calidad(plataformas, doce...",25,Sí
122,133,2020-11-20,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,35,Eventual
125,136,2020-11-22,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,21,Sí
131,142,2020-11-22,Ingeniería de Sistemas,Si,Horario flexible.,Conexión a internet.,24,Sí
135,146,2020-11-22,Ingeniería de Sistemas,Si,Autonomía.,Contacto Personal Docente-Estudiantil.,20,Sí
138,150,2020-11-22,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",26,Eventual
140,152,2020-11-22,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,20,Sí
142,154,2020-11-22,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",20,Eventual
148,160,2020-11-23,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",30,Sí
151,163,2020-11-23,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,35,Sí
173,185,2020-11-27,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,22,Eventual
178,190,2020-11-27,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,30,Sí
180,192,2020-11-27,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",26,Sí
190,202,2020-12-08,Ingeniería de Sistemas,Si,Autonomía.,Contacto Personal Docente-Estudiantil.,40,Sí
192,204,2020-12-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,23,Eventual
196,208,2020-12-08,Ingeniería de Sistemas,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,21,Sí
197,209,2020-12-08,Ingeniería de Sistemas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",40,Sí
202,214,2020-12-08,Ingeniería de Sistemas,Si,Acceso desde cualquier lugar.,Conexión a internet.,25,Sí

2. Seleccionar columnas: Selecciona solo ciertas columnas para un nuevo DataFrame.

In [27]:
df_columnas = df[["carrera", "edad", "trabajo"]]
df_columnas

                          carrera  edad   trabajo
0          Ingeniería de Sistemas    20  Eventual
1                      Psicología    26  Eventual
2          Ingeniería de Sistemas    20        Sí
3          Ingeniería de Sistemas    18        No
4          Ingeniería de Sistemas    39        Sí
..                            ...   ...       ...
217  Gestión Turística y Hotelera    19        Sí
218        Ingeniería de Sistemas    23        No
219  Gestión Turística y Hotelera    25        Sí
220         Ingeniería Agronómica    20        Sí
221        Comercio Internacional    23        Sí

[222 rows x 3 columns]

Parte 4: Operaciones y Agrupación
1. Calcula la suma, media de una columna

In [28]:
suma_edad = df["edad"].sum()
media_edad = df["edad"].mean()

print("Suma de edades:", suma_edad)
print("Edad promedio:", media_edad)

Suma de edades: 6253
Edad promedio: 28.166666666666668

2. Agrupa los datos por una columna y calcula la media de otra columna para cada grupo.

In [29]:
edad_por_carrera = df.groupby("carrera")["edad"].mean()
edad_por_carrera

carrera
Administración de Empresas                  25.375000
Artes Plásticas                             30.000000
Ciencias Físicas y Energías Alternativas    26.500000
Ciencias Políticas                          38.666667
Ciencias de la Educación                    26.153846
Comercio Internacional                      28.857143
Contaduría Pública                          29.461538
Derecho                                     32.515152
Economía                                    28.250000
Educación Parvularia                        32.333333
Gestión Turística y Hotelera                23.800000
Historia                                    25.000000
Ingeniería Agronómica                       27.166667
Ingeniería de Sistemas                      26.375000
Lingüística e Idiomas                       34.250000
Nutrición y Dietética                       31.500000
Otra                                        24.192308
Psicología                                  33.076923
Sociología                                  28.000000
Trabajo Social                              23.875000
Name: edad, dtype: float64

3. Crea una tabla pivote para resumir los datos.

In [30]:
tabla_pivote = pd.pivot_table(
    df,
    values="edad",
    index="carrera",
    aggfunc="mean"
)

tabla_pivote

                                               edad
carrera
Administración de Empresas                25.375000
Artes Plásticas                           30.000000
Ciencias Físicas y Energías Alternativas  26.500000
Ciencias Políticas                        38.666667
Ciencias de la Educación                  26.153846
Comercio Internacional                    28.857143
Contaduría Pública                        29.461538
Derecho                                   32.515152
Economía                                  28.250000
Educación Parvularia                      32.333333
Gestión Turística y Hotelera              23.800000
Historia                                  25.000000
Ingeniería Agronómica                     27.166667
Ingeniería de Sistemas                    26.375000
Lingüística e Idiomas                     34.250000
Nutrición y Dietética                     31.500000
Otra                                      24.192308
Psicología                                33.076923
Sociología                                28.000000
Trabajo Social                            23.875000

Ejercicio 5: Manipulación de Datos
1. Ordenar datos: Ordena el DataFrame por una columna específica.

In [31]:
df_ordenado = df.sort_values(by="edad", ascending=False)
df_ordenado

,Unnamed: 0,time,carrera,acepta,positivo,negativo,edad,trabajo
114,125,2020-11-19,Lingüística e Idiomas,Si,Horario flexible.,Conexión a internet.,54,Sí
64,73,2020-11-10,Lingüística e Idiomas,Si,Horario flexible.,"Falta de recursos de calidad(plataformas, doce...",50,Sí
85,95,2020-11-11,Derecho,Si,Acceso desde cualquier lugar.,Contacto Personal Docente-Estudiantil.,49,Sí
141,153,2020-11-22,Comercio Internacional,Si,Horario flexible.,Conexión a internet.,47,Sí
25,27,2020-11-09,Ciencias de la Educación,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,46,Sí
...,...,...,...,...,...,...,...,...
87,98,2020-11-13,Otra,Si,Horario flexible.,Conexión a internet.,18,No
86,96,2020-11-13,Ciencias de la Educación,Si,Acceso desde cualquier lugar.,Conexión a internet.,17,No
74,84,2020-11-10,Otra,Si,Horario flexible.,Contacto Personal Docente-Estudiantil.,17,Sí
75,85,2020-11-10,Trabajo Social,Si,Horario flexible.,Conexión a internet.,17,Sí
98,109,2020-11-14,Contaduría Pública,Si,Horario flexible.,Conexión a internet.,17,Sí

Ejercicio 6: Guardar Resultados
1. Guardar DataFrame: Guarda el DataFrame modificado en un nuevo archivo CSV.

In [32]:
df_ordenado.to_csv("modificado.csv", index=False)